#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
for f in "$HOME"/.zshrc.d/*
do
  # shellcheck disable=SC1090,SC1091
  source "$f"
done

export VISUAL=vim
export EDITOR=vim

