#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
for f in ${HOME}/.zshrc.d/*.sh
do
  source "$f"
done

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/aratana_mac52/dev/src/github.com/aratana/aratana-gateway/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/aratana_mac52/dev/src/github.com/aratana/aratana-gateway/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/aratana_mac52/dev/src/github.com/aratana/aratana-gateway/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/aratana_mac52/dev/src/github.com/aratana/aratana-gateway/node_modules/tabtab/.completions/sls.zsh

