#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
for f in `ls $HOME/.zshrc.d/*`
do
  source $f
done

export VISUAL=vim
export EDITOR=vim

# The next line updates PATH for the Google Cloud SDK.
source '/Users/eisuke/google-cloud-sdk/path.zsh.inc'

# The next line enables shell command completion for gcloud.
source '/Users/eisuke/google-cloud-sdk/completion.zsh.inc'
